language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/master/scripts/install-for-ci.sh | sh

script:
  - ros -s prove -e '(prove:run :testtravis-test)'
